networks:
  reviews_app:

services:

  frontend:
    build: frontend/
    ports:
      - "80:80" ## containerPort:hostPort
    networks:
      - reviews_app

  backend:
    build: api-backend/
    ports:
      - "3000:80"
    networks:
      - reviews_app
    environment:
      DB_USERNAME: "admin"
      DB_PASSWORD: "admin"
      DB_ENDPOINT: "database"
      DB_NAME: "reviews_db"
    depends_on: 
      - database


  database:
    build: database/
    networks:
      - reviews_app
    environment:
      MYSQL_ROOT_PASSWORD: "root_passwd"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin"
      MYSQL_DATABASE: "reviews_db"